version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$SQL_PASSWORD
      - SQL_DATABASE
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000"
    environment:
      - DB_HOST=db
      - DB_USER=$SQL_USER
      - DB_PASSWORD=$SQL_PASSWORD
      - DB_NAME=$SQL_PASSWORD
      - DB_PORT=3306
    stdin_open: true
    tty: true
    
volumes:
  db: